# NILM XGBoost Pipeline (Classifier + Regressor)
**Kaggle setup:** Settings -> Accelerator -> GPU (T4 x2 or P100). Required for `device='cuda'` below.

In [1]:
import os
import glob
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

## 1. Window shifter and data path

In [2]:
class WindowShifter:
    @staticmethod
    def shift(df, n):
        keep = df[['Time', 'Aggregate']]
        rest = df.drop(columns=['Time', 'Unix', 'Aggregate'])
        frames = [
            keep.shift(i).rename(columns={'Time': f'Time_t{i}', 'Aggregate': f'Aggregate_t{i}'})
            for i in range(n)
        ]
        return pd.concat(frames + [rest], axis=1).dropna()


data_path = '/kaggle/input/datasets/meowll/nilm-data/House2_full.csv'

## 2. Load, clean, window, and engineer features

In [3]:
df = pd.read_csv(data_path, encoding='utf-8')

app_cols = [f'Appliance{i}' for i in range(1, 10)]

# fix invalid readings where Aggregate < sum(appliances)
invalid_mask = df['Aggregate'] < df[app_cols].sum(axis=1)
df.loc[invalid_mask, app_cols] = np.nan
df[app_cols] = df[app_cols].interpolate(method='linear').bfill().ffill()
df.loc[invalid_mask, 'Aggregate'] = np.nan
df['Aggregate'] = df['Aggregate'].interpolate(method='linear').bfill().ffill()

df = WindowShifter.shift(df, 50)

aggregate_cols = [c for c in df.columns[:-9] if 'Time' not in c]
df['remain'] = (df['Aggregate_t0'] - df[app_cols].sum(axis=1)).clip(lower=0)

dt = pd.to_datetime(df['Time_t0'], format='%Y-%m-%d %H:%M:%S')
df['dow'] = dt.dt.day_of_week.astype('int8')
df['dom'] = dt.dt.day.astype('int8')
df['hour'] = dt.dt.hour.astype('int8')

# drop Time_t* columns (not used as features) and downcast to float32 to save RAM
df = df.drop(columns=[c for c in df.columns if c.startswith('Time_t')])
for c in aggregate_cols + ['remain'] + app_cols:
    df[c] = df[c].astype('float32')

df.head()

/tmp/ipykernel_58/2704847298.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['remain'] = (df['Aggregate_t0'] - df[app_cols].sum(axis=1)).clip(lower=0)
/tmp/ipykernel_58/2704847298.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['dow'] = dt.dt.day_of_week.astype('int8')
/tmp/ipykernel_58/2704847298.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['dom'] = dt.dt.day.astype('int8')
/tmp/ipykernel_58/2704847298.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['hour'] = dt.dt.hour.astype('int8')

,Aggregate_t0,Aggregate_t1,Aggregate_t2,Aggregate_t3,Aggregate_t4,Aggregate_t5,Aggregate_t6,Aggregate_t7,Aggregate_t8,Aggregate_t9,...,Appliance4,Appliance5,Appliance6,Appliance7,Appliance8,Appliance9,remain,dow,dom,hour
49,695.0,694.0,702.0,698.0,696.0,690.0,690.0,689.0,695.0,686.0,...,0.0,0.0,0.0,0.0,0.0,0.0,609.0,1,17,22
50,683.0,695.0,694.0,702.0,698.0,696.0,690.0,690.0,689.0,695.0,...,0.0,0.0,0.0,0.0,0.0,0.0,597.0,1,17,22
51,686.0,683.0,695.0,694.0,702.0,698.0,696.0,690.0,690.0,689.0,...,0.0,0.0,0.0,0.0,0.0,0.0,601.0,1,17,22
52,691.0,686.0,683.0,695.0,694.0,702.0,698.0,696.0,690.0,690.0,...,0.0,0.0,0.0,0.0,0.0,0.0,606.0,1,17,22
53,691.0,691.0,686.0,683.0,695.0,694.0,702.0,698.0,696.0,690.0,...,0.0,0.0,0.0,0.0,0.0,0.0,606.0,1,17,22

## 3. Feature/target columns and on/off thresholds

In [4]:
x_cols = ['dow', 'dom', 'hour'] + aggregate_cols
y_cols = app_cols + ['remain']

on_threshold = {
    'Appliance1': 15,   # Fridge-Freezer
    'Appliance2': 20,   # Washing Machine
    'Appliance3': 20,   # Dishwasher
    'Appliance4': 15,   # Television
    'Appliance5': 50,   # Microwave
    'Appliance6': 50,   # Toaster
    'Appliance7': 10,   # Hi-Fi
    'Appliance8': 100,  # Kettle
    'Appliance9': 5,    # Oven Extractor Fan
}

train_mask = ((df['dom'] - 1) // 7 + 1) % 2 == 0
test_mask = ~train_mask

## 4. Classifier: is appliance below the on/off threshold

In [5]:
y_class = pd.DataFrame({app: df[app] < on_threshold[app] for app in app_cols})

X_train_class, y_train_class = df.loc[train_mask, x_cols], y_class.loc[train_mask]
X_train_class, X_val_class, y_train_class, y_val_class = train_test_split(
    X_train_class, y_train_class, test_size=0.01
)
X_test_class, y_test_class = df.loc[test_mask, x_cols], y_class.loc[test_mask]

In [6]:
classifier = {}
for app in app_cols:
    clf = xgb.XGBClassifier(
        n_estimators=5000,
        learning_rate=0.05,
        early_stopping_rounds=50,
        tree_method='hist',
        device='cuda',
        eval_metric='logloss',
    )
    clf.fit(X_train_class, y_train_class[app], eval_set=[(X_val_class, y_val_class[app])], verbose=100)
    classifier[app] = clf

[0]	validation_0-logloss:0.65380
[100]	validation_0-logloss:0.36396
[200]	validation_0-logloss:0.33697
[300]	validation_0-logloss:0.31755
[400]	validation_0-logloss:0.30455
[500]	validation_0-logloss:0.29398
[600]	validation_0-logloss:0.28480
[700]	validation_0-logloss:0.27825
[800]	validation_0-logloss:0.27052
[900]	validation_0-logloss:0.26497
[1000]	validation_0-logloss:0.25908
[1100]	validation_0-logloss:0.25373
[1200]	validation_0-logloss:0.24982
[1300]	validation_0-logloss:0.24518
[1400]	validation_0-logloss:0.24079
[1500]	validation_0-logloss:0.23686
[1600]	validation_0-logloss:0.23368
[1700]	validation_0-logloss:0.23038
[1800]	validation_0-logloss:0.22743
[1900]	validation_0-logloss:0.22427
[2000]	validation_0-logloss:0.22202
[2100]	validation_0-logloss:0.21831
[2200]	validation_0-logloss:0.21655
[2300]	validation_0-logloss:0.21359
[2400]	validation_0-logloss:0.21131
[2500]	validation_0-logloss:0.20771
[2600]	validation_0-logloss:0.20568
[2700]	validation_0-logloss:0.20352
[2800]	validation_0-logloss:0.20123
[2900]	validation_0-logloss:0.19922
[3000]	validation_0-logloss:0.19724
[3100]	validation_0-logloss:0.19508
[3200]	validation_0-logloss:0.19338
[3300]	validation_0-logloss:0.19128
[3400]	validation_0-logloss:0.18937
[3500]	validation_0-logloss:0.18797
[3600]	validation_0-logloss:0.18596
[3700]	validation_0-logloss:0.18444
[3800]	validation_0-logloss:0.18318
[3900]	validation_0-logloss:0.18105
[4000]	validation_0-logloss:0.17976
[4100]	validation_0-logloss:0.17846
[4200]	validation_0-logloss:0.17675
[4300]	validation_0-logloss:0.17531
[4400]	validation_0-logloss:0.17359
[4500]	validation_0-logloss:0.17229
[4600]	validation_0-logloss:0.17050
[4700]	validation_0-logloss:0.16933
[4800]	validation_0-logloss:0.16768
[4900]	validation_0-logloss:0.16635
[4999]	validation_0-logloss:0.16521
[0]	validation_0-logloss:0.16014
[100]	validation_0-logloss:0.08746
[200]	validation_0-logloss:0.07078
[300]	validation_0-logloss:0.06299
[400]	validation_0-logloss:0.05721
[500]	validation_0-logloss:0.05309
[600]	validation_0-logloss:0.04960
[700]	validation_0-logloss:0.04699
[800]	validation_0-logloss:0.04497
[900]	validation_0-logloss:0.04307
[1000]	validation_0-logloss:0.04162
[1100]	validation_0-logloss:0.04063
[1200]	validation_0-logloss:0.03947
[1300]	validation_0-logloss:0.03873
[1400]	validation_0-logloss:0.03787
[1500]	validation_0-logloss:0.03727
[1600]	validation_0-logloss:0.03641
[1700]	validation_0-logloss:0.03595
[1800]	validation_0-logloss:0.03539
[1900]	validation_0-logloss:0.03481
[2000]	validation_0-logloss:0.03436
[2100]	validation_0-logloss:0.03373
[2200]	validation_0-logloss:0.03335
[2300]	validation_0-logloss:0.03295
[2400]	validation_0-logloss:0.03262
[2500]	validation_0-logloss:0.03223
[2600]	validation_0-logloss:0.03189
[2700]	validation_0-logloss:0.03155
[2800]	validation_0-logloss:0.03135
[2900]	validation_0-logloss:0.03112
[3000]	validation_0-logloss:0.03086
[3100]	validation_0-logloss:0.03064
[3200]	validation_0-logloss:0.03048
[3300]	validation_0-logloss:0.03030
[3400]	validation_0-logloss:0.03013
[3500]	validation_0-logloss:0.03001
[3600]	validation_0-logloss:0.02988
[3700]	validation_0-logloss:0.02965
[3800]	validation_0-logloss:0.02951
[3900]	validation_0-logloss:0.02932
[4000]	validation_0-logloss:0.02919
[4100]	validation_0-logloss:0.02908
[4200]	validation_0-logloss:0.02894
[4300]	validation_0-logloss:0.02875
[4400]	validation_0-logloss:0.02858
[4500]	validation_0-logloss:0.02851
[4600]	validation_0-logloss:0.02845
[4700]	validation_0-logloss:0.02829
[4800]	validation_0-logloss:0.02823
[4900]	validation_0-logloss:0.02822
[4999]	validation_0-logloss:0.02814
[0]	validation_0-logloss:0.25758
[100]	validation_0-logloss:0.15154
[200]	validation_0-logloss:0.13252
[300]	validation_0-logloss:0.12101
[400]	validation_0-logloss:0.11222
[500]	validation_0-logloss:0.10400
[600]	validation_0-logloss:0.09889
[700]	validation_0-logloss:0.09462
[800]	validation_0-logloss:0.08977
[900]	validation_0-logloss:0.08738
[1000]	validation_0-logloss:0.08422
[1100]	validation_0-logloss:0.08125
[1200]	validation_0-logloss:0.07875
[1300]	validation_0-logloss:0.07573
[1400]	validation_0-logloss:0.07351
[1500]	validation_0-logloss:0.07030
[1600]	validation_0-logloss:0.06875
[1700]	validation_0-logloss:0.06609
[1800]	validation_0-logloss:0.06406
[1900]	validation_0-logloss:0.06286
[2000]	validation_0-logloss:0.06172
[2100]	validation_0-logloss:0.06037
[2200]	validation_0-logloss:0.05852
[2300]	validation_0-logloss:0.05729
[2400]	validation_0-logloss:0.05591
[2500]	validation_0-logloss:0.05439
[2600]	validation_0-logloss:0.05332
[2700]	validation_0-logloss:0.05217
[2800]	validation_0-logloss:0.05145
[2900]	validation_0-logloss:0.05035
[3000]	validation_0-logloss:0.04918
[3100]	validation_0-logloss:0.04841
[3200]	validation_0-logloss:0.04707
[3300]	validation_0-logloss:0.04595
[3400]	validation_0-logloss:0.04518
[3500]	validation_0-logloss:0.04451
[3600]	validation_0-logloss:0.04368
[3700]	validation_0-logloss:0.04298
[3800]	validation_0-logloss:0.04227
[3900]	validation_0-logloss:0.04180
[4000]	validation_0-logloss:0.04126
[4100]	validation_0-logloss:0.04067
[4200]	validation_0-logloss:0.04009
[4300]	validation_0-logloss:0.03927
[4400]	validation_0-logloss:0.03874
[4500]	validation_0-logloss:0.03826
[4600]	validation_0-logloss:0.03782
[4700]	validation_0-logloss:0.03709
[4800]	validation_0-logloss:0.03647
[4900]	validation_0-logloss:0.03584
[4999]	validation_0-logloss:0.03522
[0]	validation_0-logloss:0.30817
[100]	validation_0-logloss:0.20281
[200]	validation_0-logloss:0.17950
[300]	validation_0-logloss:0.16467
[400]	validation_0-logloss:0.15294
[500]	validation_0-logloss:0.14415
[600]	validation_0-logloss:0.13657
[700]	validation_0-logloss:0.13171
[800]	validation_0-logloss:0.12772
[900]	validation_0-logloss:0.12282
[1000]	validation_0-logloss:0.11856
[1100]	validation_0-logloss:0.11544
[1200]	validation_0-logloss:0.11145
[1300]	validation_0-logloss:0.10867
[1400]	validation_0-logloss:0.10543
[1500]	validation_0-logloss:0.10175
[1600]	validation_0-logloss:0.09897
[1700]	validation_0-logloss:0.09645
[1800]	validation_0-logloss:0.09475
[1900]	validation_0-logloss:0.09259
[2000]	validation_0-logloss:0.09037
[2100]	validation_0-logloss:0.08822
[2200]	validation_0-logloss:0.08607
[2300]	validation_0-logloss:0.08437
[2400]	validation_0-logloss:0.08276
[2500]	validation_0-logloss:0.08143
[2600]	validation_0-logloss:0.07953
[2700]	validation_0-logloss:0.07831
[2800]	validation_0-logloss:0.07676
[2900]	validation_0-logloss:0.07454
[3000]	validation_0-logloss:0.07272
[3100]	validation_0-logloss:0.07126
[3200]	validation_0-logloss:0.07000
[3300]	validation_0-logloss:0.06894
[3400]	validation_0-logloss:0.06765
[3500]	validation_0-logloss:0.06591
[3600]	validation_0-logloss:0.06478
[3700]	validation_0-logloss:0.06367
[3800]	validation_0-logloss:0.06265
[3900]	validation_0-logloss:0.06174
[4000]	validation_0-logloss:0.06086
[4100]	validation_0-logloss:0.05979
[4200]	validation_0-logloss:0.05889
[4300]	validation_0-logloss:0.05808
[4400]	validation_0-logloss:0.05711
[4500]	validation_0-logloss:0.05597
[4600]	validation_0-logloss:0.05494
[4700]	validation_0-logloss:0.05420
[4800]	validation_0-logloss:0.05370
[4900]	validation_0-logloss:0.05274
[4999]	validation_0-logloss:0.05210
[0]	validation_0-logloss:0.01443
[100]	validation_0-logloss:0.00675
[200]	validation_0-logloss:0.00582
[300]	validation_0-logloss:0.00518
[400]	validation_0-logloss:0.00475
[500]	validation_0-logloss:0.00442
[600]	validation_0-logloss:0.00418
[700]	validation_0-logloss:0.00397
[800]	validation_0-logloss:0.00379
[900]	validation_0-logloss:0.00363
[1000]	validation_0-logloss:0.00349
[1100]	validation_0-logloss:0.00336
[1200]	validation_0-logloss:0.00329
[1300]	validation_0-logloss:0.00318
[1400]	validation_0-logloss:0.00312
[1500]	validation_0-logloss:0.00305
[1600]	validation_0-logloss:0.00299
[1700]	validation_0-logloss:0.00295
[1800]	validation_0-logloss:0.00293
[1900]	validation_0-logloss:0.00290
[2000]	validation_0-logloss:0.00288
[2100]	validation_0-logloss:0.00283
[2200]	validation_0-logloss:0.00281
[2291]	validation_0-logloss:0.00281
[0]	validation_0-logloss:0.00825
[100]	validation_0-logloss:0.00265
[200]	validation_0-logloss:0.00192
[300]	validation_0-logloss:0.00153
[400]	validation_0-logloss:0.00132
[500]	validation_0-logloss:0.00120
[600]	validation_0-logloss:0.00112
[700]	validation_0-logloss:0.00105
[800]	validation_0-logloss:0.00101
[900]	validation_0-logloss:0.00095
[1000]	validation_0-logloss:0.00088
[1100]	validation_0-logloss:0.00084
[1200]	validation_0-logloss:0.00080
[1300]	validation_0-logloss:0.00077
[1400]	validation_0-logloss:0.00074
[1500]	validation_0-logloss:0.00073
[1600]	validation_0-logloss:0.00072
[1700]	validation_0-logloss:0.00071
[1728]	validation_0-logloss:0.00071
[0]	validation_0-logloss:0.33709
[100]	validation_0-logloss:0.20197
[200]	validation_0-logloss:0.16678
[300]	validation_0-logloss:0.14447
[400]	validation_0-logloss:0.12477
[500]	validation_0-logloss:0.11492
[600]	validation_0-logloss:0.10535
[700]	validation_0-logloss:0.09652
[800]	validation_0-logloss:0.08945
[900]	validation_0-logloss:0.08312
[1000]	validation_0-logloss:0.07866
[1100]	validation_0-logloss:0.07423
[1200]	validation_0-logloss:0.07088
[1300]	validation_0-logloss:0.06677
[1400]	validation_0-logloss:0.06362
[1500]	validation_0-logloss:0.06103
[1600]	validation_0-logloss:0.05832
[1700]	validation_0-logloss:0.05536
[1800]	validation_0-logloss:0.05275
[1900]	validation_0-logloss:0.05043
[2000]	validation_0-logloss:0.04779
[2100]	validation_0-logloss:0.04590
[2200]	validation_0-logloss:0.04425
[2300]	validation_0-logloss:0.04289
[2400]	validation_0-logloss:0.04160
[2500]	validation_0-logloss:0.04046
[2600]	validation_0-logloss:0.03918
[2700]	validation_0-logloss:0.03776
[2800]	validation_0-logloss:0.03651
[2900]	validation_0-logloss:0.03572
[3000]	validation_0-logloss:0.03495
[3100]	validation_0-logloss:0.03404
[3200]	validation_0-logloss:0.03339
[3300]	validation_0-logloss:0.03256
[3400]	validation_0-logloss:0.03164
[3500]	validation_0-logloss:0.03089
[3600]	validation_0-logloss:0.03001
[3700]	validation_0-logloss:0.02910
[3800]	validation_0-logloss:0.02835
[3900]	validation_0-logloss:0.02772
[4000]	validation_0-logloss:0.02712
[4100]	validation_0-logloss:0.02656
[4200]	validation_0-logloss:0.02582
[4300]	validation_0-logloss:0.02517
[4400]	validation_0-logloss:0.02454
[4500]	validation_0-logloss:0.02401
[4600]	validation_0-logloss:0.02358
[4700]	validation_0-logloss:0.02313
[4800]	validation_0-logloss:0.02264
[4900]	validation_0-logloss:0.02225
[4999]	validation_0-logloss:0.02190
[0]	validation_0-logloss:0.02272
[100]	validation_0-logloss:0.00648
[200]	validation_0-logloss:0.00551
[300]	validation_0-logloss:0.00496
[400]	validation_0-logloss:0.00458
[500]	validation_0-logloss:0.00429
[600]	validation_0-logloss:0.00412
[700]	validation_0-logloss:0.00389
[800]	validation_0-logloss:0.00375
[900]	validation_0-logloss:0.00364
[1000]	validation_0-logloss:0.00356
[1100]	validation_0-logloss:0.00346
[1200]	validation_0-logloss:0.00337
[1300]	validation_0-logloss:0.00330
[1400]	validation_0-logloss:0.00320
[1500]	validation_0-logloss:0.00314
[1519]	validation_0-logloss:0.00314
[0]	validation_0-logloss:0.03482
[100]	validation_0-logloss:0.01523
[200]	validation_0-logloss:0.01102
[300]	validation_0-logloss:0.00869
[400]	validation_0-logloss:0.00714
[500]	validation_0-logloss:0.00610
[600]	validation_0-logloss:0.00509
[700]	validation_0-logloss:0.00449
[800]	validation_0-logloss:0.00402
[900]	validation_0-logloss:0.00358
[1000]	validation_0-logloss:0.00318
[1100]	validation_0-logloss:0.00289
[1200]	validation_0-logloss:0.00262
[1300]	validation_0-logloss:0.00244
[1400]	validation_0-logloss:0.00225
[1500]	validation_0-logloss:0.00212
[1600]	validation_0-logloss:0.00196
[1700]	validation_0-logloss:0.00184
[1800]	validation_0-logloss:0.00174
[1900]	validation_0-logloss:0.00166
[2000]	validation_0-logloss:0.00158
[2100]	validation_0-logloss:0.00151
[2200]	validation_0-logloss:0.00145
[2300]	validation_0-logloss:0.00141
[2400]	validation_0-logloss:0.00137
[2500]	validation_0-logloss:0.00133
[2600]	validation_0-logloss:0.00129
[2700]	validation_0-logloss:0.00126
[2800]	validation_0-logloss:0.00124
[2900]	validation_0-logloss:0.00121
[3000]	validation_0-logloss:0.00118
[3100]	validation_0-logloss:0.00115
[3200]	validation_0-logloss:0.00112
[3300]	validation_0-logloss:0.00111
[3400]	validation_0-logloss:0.00109
[3500]	validation_0-logloss:0.00107
[3600]	validation_0-logloss:0.00105
[3700]	validation_0-logloss:0.00104
[3730]	validation_0-logloss:0.00104

In [7]:
clf_f1 = {app: f1_score(classifier[app].predict(X_test_class), y_test_class[app]) for app in app_cols}
pd.Series(clf_f1, name='F1 (on/off)')

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [20:23:42] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

Appliance1    0.840209
Appliance2    0.983682
Appliance3    0.957432
Appliance4    0.944372
Appliance5    0.999012
Appliance6    0.999435
Appliance7    0.907283
Appliance8    0.998753
Appliance9    0.997417
Name: F1 (on/off), dtype: float64

## 5. Regressor: predict power draw per appliance

In [8]:
X_train, y_train = df.loc[train_mask, x_cols], df.loc[train_mask, y_cols]
X_test, y_test = df.loc[test_mask, x_cols][:70000], df.loc[test_mask, y_cols][:70000]
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.05)

In [9]:
regressor = {}
for app in app_cols:
    model = xgb.XGBRegressor(
        n_estimators=5000,
        learning_rate=0.05,
        early_stopping_rounds=50,
        tree_method='hist',
        device='cuda',
    )
    model.fit(X_train, y_train[app], eval_set=[(X_val, y_val[app])], verbose=100)
    regressor[app] = model

[0]	validation_0-rmse:42.53972
[100]	validation_0-rmse:31.18561
[200]	validation_0-rmse:29.82659
[300]	validation_0-rmse:29.04990
[400]	validation_0-rmse:28.42667
[500]	validation_0-rmse:27.94841
[600]	validation_0-rmse:27.52973
[700]	validation_0-rmse:27.03447
[800]	validation_0-rmse:26.79405
[900]	validation_0-rmse:26.54495
[1000]	validation_0-rmse:26.30208
[1100]	validation_0-rmse:25.99677
[1200]	validation_0-rmse:25.81214
[1300]	validation_0-rmse:25.60317
[1400]	validation_0-rmse:25.44133
[1500]	validation_0-rmse:25.23084
[1600]	validation_0-rmse:25.07256
[1700]	validation_0-rmse:24.95607
[1800]	validation_0-rmse:24.75033
[1900]	validation_0-rmse:24.59838
[2000]	validation_0-rmse:24.41173
[2100]	validation_0-rmse:24.21691
[2200]	validation_0-rmse:24.08415
[2300]	validation_0-rmse:23.95492
[2400]	validation_0-rmse:23.77556
[2500]	validation_0-rmse:23.63110
[2600]	validation_0-rmse:23.51521
[2700]	validation_0-rmse:23.37146
[2800]	validation_0-rmse:23.22554
[2900]	validation_0-rmse:23.11835
[3000]	validation_0-rmse:23.03624
[3100]	validation_0-rmse:22.91953
[3200]	validation_0-rmse:22.80391
[3300]	validation_0-rmse:22.69216
[3400]	validation_0-rmse:22.59425
[3500]	validation_0-rmse:22.48856
[3600]	validation_0-rmse:22.38818
[3700]	validation_0-rmse:22.29650
[3800]	validation_0-rmse:22.19598
[3900]	validation_0-rmse:22.11854
[4000]	validation_0-rmse:22.00889
[4100]	validation_0-rmse:21.90499
[4200]	validation_0-rmse:21.83084
[4300]	validation_0-rmse:21.76344
[4400]	validation_0-rmse:21.68835
[4500]	validation_0-rmse:21.60499
[4600]	validation_0-rmse:21.51425
[4700]	validation_0-rmse:21.46532
[4800]	validation_0-rmse:21.40541
[4900]	validation_0-rmse:21.35634
[4999]	validation_0-rmse:21.29066
[0]	validation_0-rmse:167.36898
[100]	validation_0-rmse:122.94830
[200]	validation_0-rmse:110.86836
[300]	validation_0-rmse:103.53745
[400]	validation_0-rmse:98.54112
[500]	validation_0-rmse:95.14606
[600]	validation_0-rmse:92.77862
[700]	validation_0-rmse:89.81550
[800]	validation_0-rmse:87.68547
[900]	validation_0-rmse:85.55426
[1000]	validation_0-rmse:84.14275
[1100]	validation_0-rmse:82.73545
[1200]	validation_0-rmse:81.17581
[1300]	validation_0-rmse:79.93539
[1400]	validation_0-rmse:78.78367
[1500]	validation_0-rmse:77.84244
[1600]	validation_0-rmse:77.08524
[1700]	validation_0-rmse:76.27860
[1800]	validation_0-rmse:75.43348
[1900]	validation_0-rmse:74.50576
[2000]	validation_0-rmse:73.66634
[2100]	validation_0-rmse:73.00483
[2200]	validation_0-rmse:72.44236
[2300]	validation_0-rmse:71.88934
[2400]	validation_0-rmse:71.22351
[2500]	validation_0-rmse:70.65011
[2600]	validation_0-rmse:70.08693
[2700]	validation_0-rmse:69.53418
[2800]	validation_0-rmse:69.10287
[2900]	validation_0-rmse:68.56845
[3000]	validation_0-rmse:68.21726
[3100]	validation_0-rmse:67.84445
[3200]	validation_0-rmse:67.49666
[3300]	validation_0-rmse:67.09943
[3400]	validation_0-rmse:66.66984
[3500]	validation_0-rmse:66.24351
[3600]	validation_0-rmse:65.95396
[3700]	validation_0-rmse:65.56869
[3800]	validation_0-rmse:65.31333
[3900]	validation_0-rmse:65.07197
[4000]	validation_0-rmse:64.82218
[4100]	validation_0-rmse:64.57641
[4200]	validation_0-rmse:64.32123
[4300]	validation_0-rmse:64.04009
[4400]	validation_0-rmse:63.80554
[4500]	validation_0-rmse:63.55282
[4600]	validation_0-rmse:63.29695
[4700]	validation_0-rmse:62.97625
[4800]	validation_0-rmse:62.74571
[4900]	validation_0-rmse:62.46299
[4999]	validation_0-rmse:62.23981
[0]	validation_0-rmse:329.35616
[100]	validation_0-rmse:175.92087
[200]	validation_0-rmse:160.80582
[300]	validation_0-rmse:151.49021
[400]	validation_0-rmse:145.12238
[500]	validation_0-rmse:139.11175
[600]	validation_0-rmse:132.55797
[700]	validation_0-rmse:128.71832
[800]	validation_0-rmse:125.14469
[900]	validation_0-rmse:121.83625
[1000]	validation_0-rmse:119.23749
[1100]	validation_0-rmse:117.07202
[1200]	validation_0-rmse:114.53675
[1300]	validation_0-rmse:112.58803
[1400]	validation_0-rmse:111.04871
[1500]	validation_0-rmse:109.26244
[1600]	validation_0-rmse:107.60766
[1700]	validation_0-rmse:106.22354
[1800]	validation_0-rmse:104.83158
[1900]	validation_0-rmse:103.47498
[2000]	validation_0-rmse:102.40979
[2100]	validation_0-rmse:101.51479
[2200]	validation_0-rmse:100.47851
[2300]	validation_0-rmse:99.69347
[2400]	validation_0-rmse:98.87909
[2500]	validation_0-rmse:98.10354
[2600]	validation_0-rmse:97.29544
[2700]	validation_0-rmse:96.34051
[2800]	validation_0-rmse:95.58514
[2900]	validation_0-rmse:95.01682
[3000]	validation_0-rmse:94.36953
[3100]	validation_0-rmse:93.89486
[3200]	validation_0-rmse:93.21901
[3300]	validation_0-rmse:92.70759
[3400]	validation_0-rmse:92.01031
[3500]	validation_0-rmse:91.39583
[3600]	validation_0-rmse:90.81435
[3700]	validation_0-rmse:90.37612
[3800]	validation_0-rmse:90.06070
[3900]	validation_0-rmse:89.61898
[4000]	validation_0-rmse:89.21432
[4100]	validation_0-rmse:88.73025
[4200]	validation_0-rmse:88.31275
[4300]	validation_0-rmse:87.92193
[4400]	validation_0-rmse:87.49912
[4500]	validation_0-rmse:87.20157
[4600]	validation_0-rmse:86.74487
[4700]	validation_0-rmse:86.30391
[4800]	validation_0-rmse:85.96969
[4900]	validation_0-rmse:85.74740
[4999]	validation_0-rmse:85.51987
[0]	validation_0-rmse:12.84429
[100]	validation_0-rmse:10.67452
[200]	validation_0-rmse:10.20677
[300]	validation_0-rmse:9.92508
[400]	validation_0-rmse:9.68337
[500]	validation_0-rmse:9.54679
[600]	validation_0-rmse:9.41588
[700]	validation_0-rmse:9.30978
[800]	validation_0-rmse:9.22166
[900]	validation_0-rmse:9.09038
[1000]	validation_0-rmse:8.96811
[1100]	validation_0-rmse:8.87590
[1200]	validation_0-rmse:8.75299
[1300]	validation_0-rmse:8.66532
[1400]	validation_0-rmse:8.58529
[1500]	validation_0-rmse:8.50880
[1600]	validation_0-rmse:8.43857
[1700]	validation_0-rmse:8.37239
[1800]	validation_0-rmse:8.31510
[1900]	validation_0-rmse:8.24206
[2000]	validation_0-rmse:8.18831
[2100]	validation_0-rmse:8.12275
[2200]	validation_0-rmse:8.06517
[2300]	validation_0-rmse:8.00973
[2400]	validation_0-rmse:7.94503
[2500]	validation_0-rmse:7.87884
[2600]	validation_0-rmse:7.81630
[2700]	validation_0-rmse:7.77737
[2800]	validation_0-rmse:7.74633
[2900]	validation_0-rmse:7.71677
[3000]	validation_0-rmse:7.67487
[3100]	validation_0-rmse:7.63473
[3200]	validation_0-rmse:7.59460
[3300]	validation_0-rmse:7.55871
[3400]	validation_0-rmse:7.51580
[3500]	validation_0-rmse:7.47921
[3600]	validation_0-rmse:7.45171
[3700]	validation_0-rmse:7.40805
[3800]	validation_0-rmse:7.36651
[3900]	validation_0-rmse:7.32636
[4000]	validation_0-rmse:7.29692
[4100]	validation_0-rmse:7.27333
[4200]	validation_0-rmse:7.24730
[4300]	validation_0-rmse:7.21532
[4400]	validation_0-rmse:7.18610
[4500]	validation_0-rmse:7.15031
[4600]	validation_0-rmse:7.12382
[4700]	validation_0-rmse:7.09723
[4800]	validation_0-rmse:7.06734
[4900]	validation_0-rmse:7.04181
[4999]	validation_0-rmse:7.01324
[0]	validation_0-rmse:55.90766
[100]	validation_0-rmse:39.43823
[200]	validation_0-rmse:37.31524
[300]	validation_0-rmse:36.21161
[400]	validation_0-rmse:35.29071
[500]	validation_0-rmse:34.74097
[600]	validation_0-rmse:34.30599
[700]	validation_0-rmse:33.84619
[800]	validation_0-rmse:33.45087
[900]	validation_0-rmse:33.10842
[1000]	validation_0-rmse:32.88017
[1100]	validation_0-rmse:32.52147
[1200]	validation_0-rmse:32.29391
[1300]	validation_0-rmse:32.04922
[1400]	validation_0-rmse:31.86638
[1500]	validation_0-rmse:31.67490
[1600]	validation_0-rmse:31.45929
[1700]	validation_0-rmse:31.33274
[1800]	validation_0-rmse:31.19848
[1900]	validation_0-rmse:31.08335
[2000]	validation_0-rmse:30.97259
[2100]	validation_0-rmse:30.85626
[2200]	validation_0-rmse:30.75615
[2300]	validation_0-rmse:30.69982
[2400]	validation_0-rmse:30.58705
[2500]	validation_0-rmse:30.48762
[2600]	validation_0-rmse:30.42010
[2700]	validation_0-rmse:30.36248
[2800]	validation_0-rmse:30.27250
[2900]	validation_0-rmse:30.21728
[3000]	validation_0-rmse:30.17926
[3100]	validation_0-rmse:30.12496
[3200]	validation_0-rmse:30.06218
[3300]	validation_0-rmse:30.01687
[3400]	validation_0-rmse:29.97573
[3500]	validation_0-rmse:29.92627
[3600]	validation_0-rmse:29.89405
[3700]	validation_0-rmse:29.86243
[3800]	validation_0-rmse:29.81796
[3900]	validation_0-rmse:29.78047
[4000]	validation_0-rmse:29.72954
[4100]	validation_0-rmse:29.68221
[4200]	validation_0-rmse:29.63498
[4300]	validation_0-rmse:29.58863
[4400]	validation_0-rmse:29.53892
[4500]	validation_0-rmse:29.49545
[4600]	validation_0-rmse:29.46483
[4700]	validation_0-rmse:29.42566
[4800]	validation_0-rmse:29.40085
[4900]	validation_0-rmse:29.38534
[4999]	validation_0-rmse:29.36124
[0]	validation_0-rmse:33.65814
[100]	validation_0-rmse:22.06786
[200]	validation_0-rmse:20.31302
[300]	validation_0-rmse:18.99439
[400]	validation_0-rmse:18.14356
[500]	validation_0-rmse:17.59559
[600]	validation_0-rmse:17.06073
[700]	validation_0-rmse:16.66569
[800]	validation_0-rmse:16.30529
[900]	validation_0-rmse:16.06796
[1000]	validation_0-rmse:15.79867
[1100]	validation_0-rmse:15.53794
[1200]	validation_0-rmse:15.32292
[1300]	validation_0-rmse:15.14840
[1400]	validation_0-rmse:14.94959
[1500]	validation_0-rmse:14.77937
[1600]	validation_0-rmse:14.62404
[1700]	validation_0-rmse:14.44655
[1800]	validation_0-rmse:14.32066
[1900]	validation_0-rmse:14.22469
[2000]	validation_0-rmse:14.13177
[2100]	validation_0-rmse:14.03254
[2200]	validation_0-rmse:13.95271
[2300]	validation_0-rmse:13.88482
[2400]	validation_0-rmse:13.82717
[2500]	validation_0-rmse:13.74005
[2600]	validation_0-rmse:13.70200
[2700]	validation_0-rmse:13.64341
[2800]	validation_0-rmse:13.58739
[2900]	validation_0-rmse:13.53516
[3000]	validation_0-rmse:13.48961
[3100]	validation_0-rmse:13.43938
[3200]	validation_0-rmse:13.40298
[3300]	validation_0-rmse:13.35741
[3400]	validation_0-rmse:13.29192
[3500]	validation_0-rmse:13.25509
[3600]	validation_0-rmse:13.21446
[3700]	validation_0-rmse:13.15945
[3800]	validation_0-rmse:13.12045
[3900]	validation_0-rmse:13.08890
[4000]	validation_0-rmse:13.04886
[4100]	validation_0-rmse:13.01851
[4200]	validation_0-rmse:12.99726
[4300]	validation_0-rmse:12.95575
[4400]	validation_0-rmse:12.92400
[4500]	validation_0-rmse:12.89587
[4600]	validation_0-rmse:12.88528
[4700]	validation_0-rmse:12.86794
[4800]	validation_0-rmse:12.84197
[4900]	validation_0-rmse:12.83037
[4999]	validation_0-rmse:12.81499
[0]	validation_0-rmse:4.94084
[100]	validation_0-rmse:3.93742
[200]	validation_0-rmse:3.68758
[300]	validation_0-rmse:3.50871
[400]	validation_0-rmse:3.36262
[500]	validation_0-rmse:3.22966
[600]	validation_0-rmse:3.11763
[700]	validation_0-rmse:3.03940
[800]	validation_0-rmse:2.95998
[900]	validation_0-rmse:2.88865
[1000]	validation_0-rmse:2.83790
[1100]	validation_0-rmse:2.79271
[1200]	validation_0-rmse:2.76311
[1300]	validation_0-rmse:2.71477
[1400]	validation_0-rmse:2.68677
[1500]	validation_0-rmse:2.65305
[1600]	validation_0-rmse:2.61932
[1700]	validation_0-rmse:2.59243
[1800]	validation_0-rmse:2.56632
[1900]	validation_0-rmse:2.53964
[2000]	validation_0-rmse:2.51962
[2100]	validation_0-rmse:2.50027
[2200]	validation_0-rmse:2.48050
[2300]	validation_0-rmse:2.46035
[2400]	validation_0-rmse:2.43668
[2500]	validation_0-rmse:2.41105
[2600]	validation_0-rmse:2.39251
[2700]	validation_0-rmse:2.37929
[2800]	validation_0-rmse:2.36649
[2900]	validation_0-rmse:2.34810
[3000]	validation_0-rmse:2.33030
[3100]	validation_0-rmse:2.31761
[3200]	validation_0-rmse:2.30325
[3300]	validation_0-rmse:2.28708
[3400]	validation_0-rmse:2.27200
[3500]	validation_0-rmse:2.25936
[3600]	validation_0-rmse:2.24574
[3700]	validation_0-rmse:2.23544
[3800]	validation_0-rmse:2.22140
[3900]	validation_0-rmse:2.21014
[4000]	validation_0-rmse:2.19688
[4100]	validation_0-rmse:2.18592
[4200]	validation_0-rmse:2.17577
[4300]	validation_0-rmse:2.16926
[4400]	validation_0-rmse:2.15918
[4500]	validation_0-rmse:2.15076
[4600]	validation_0-rmse:2.14021
[4700]	validation_0-rmse:2.12956
[4800]	validation_0-rmse:2.11923
[4900]	validation_0-rmse:2.10658
[4999]	validation_0-rmse:2.09774
[0]	validation_0-rmse:242.39724
[100]	validation_0-rmse:106.34065
[200]	validation_0-rmse:100.03170
[300]	validation_0-rmse:95.93043
[400]	validation_0-rmse:93.34903
[500]	validation_0-rmse:91.42054
[600]	validation_0-rmse:89.37296
[700]	validation_0-rmse:88.08303
[800]	validation_0-rmse:86.74950
[900]	validation_0-rmse:85.39203
[1000]	validation_0-rmse:84.36103
[1100]	validation_0-rmse:83.58018
[1200]	validation_0-rmse:82.61882
[1300]	validation_0-rmse:82.10731
[1400]	validation_0-rmse:81.42872
[1500]	validation_0-rmse:80.92353
[1600]	validation_0-rmse:80.44280
[1700]	validation_0-rmse:79.95183
[1800]	validation_0-rmse:79.64061
[1900]	validation_0-rmse:79.30497
[2000]	validation_0-rmse:79.02068
[2100]	validation_0-rmse:78.84344
[2200]	validation_0-rmse:78.54598
[2300]	validation_0-rmse:78.27736
[2400]	validation_0-rmse:78.05814
[2500]	validation_0-rmse:77.86486
[2600]	validation_0-rmse:77.50244
[2700]	validation_0-rmse:77.23868
[2800]	validation_0-rmse:77.00557
[2900]	validation_0-rmse:76.83690
[3000]	validation_0-rmse:76.65699
[3100]	validation_0-rmse:76.47937
[3200]	validation_0-rmse:76.31514
[3300]	validation_0-rmse:76.16925
[3400]	validation_0-rmse:76.04822
[3500]	validation_0-rmse:75.87654
[3600]	validation_0-rmse:75.73695
[3700]	validation_0-rmse:75.61418
[3800]	validation_0-rmse:75.46090
[3900]	validation_0-rmse:75.35778
[4000]	validation_0-rmse:75.23774
[4100]	validation_0-rmse:75.12012
[4200]	validation_0-rmse:75.00845
[4300]	validation_0-rmse:74.87663
[4400]	validation_0-rmse:74.77905
[4500]	validation_0-rmse:74.63059
[4600]	validation_0-rmse:74.50465
[4700]	validation_0-rmse:74.45469
[4800]	validation_0-rmse:74.36189
[4900]	validation_0-rmse:74.32225
[4999]	validation_0-rmse:74.26170
[0]	validation_0-rmse:5.82988
[100]	validation_0-rmse:4.71473
[200]	validation_0-rmse:4.37834
[300]	validation_0-rmse:4.20353
[400]	validation_0-rmse:4.05350
[500]	validation_0-rmse:3.95875
[600]	validation_0-rmse:3.84668
[700]	validation_0-rmse:3.75161
[800]	validation_0-rmse:3.68863
[900]	validation_0-rmse:3.62584
[1000]	validation_0-rmse:3.56895
[1100]	validation_0-rmse:3.52426
[1200]	validation_0-rmse:3.48411
[1300]	validation_0-rmse:3.43497
[1400]	validation_0-rmse:3.39273
[1500]	validation_0-rmse:3.35792
[1600]	validation_0-rmse:3.32436
[1700]	validation_0-rmse:3.29472
[1800]	validation_0-rmse:3.26601
[1900]	validation_0-rmse:3.23160
[2000]	validation_0-rmse:3.20630
[2100]	validation_0-rmse:3.18027
[2200]	validation_0-rmse:3.15465
[2300]	validation_0-rmse:3.13390
[2400]	validation_0-rmse:3.11576
[2500]	validation_0-rmse:3.09119
[2600]	validation_0-rmse:3.06952
[2700]	validation_0-rmse:3.04002
[2800]	validation_0-rmse:3.01914
[2900]	validation_0-rmse:2.99628
[3000]	validation_0-rmse:2.97016
[3100]	validation_0-rmse:2.95230
[3200]	validation_0-rmse:2.93575
[3300]	validation_0-rmse:2.91712
[3400]	validation_0-rmse:2.90243
[3500]	validation_0-rmse:2.88030
[3600]	validation_0-rmse:2.86347
[3700]	validation_0-rmse:2.84866
[3800]	validation_0-rmse:2.83118
[3900]	validation_0-rmse:2.81141
[4000]	validation_0-rmse:2.78957
[4100]	validation_0-rmse:2.77719
[4200]	validation_0-rmse:2.76662
[4300]	validation_0-rmse:2.75475
[4400]	validation_0-rmse:2.74131
[4500]	validation_0-rmse:2.72266
[4600]	validation_0-rmse:2.71163
[4700]	validation_0-rmse:2.69404
[4800]	validation_0-rmse:2.68363
[4900]	validation_0-rmse:2.66962
[4999]	validation_0-rmse:2.66241

## 6. Inference and energy-based evaluation

In [10]:
pred = [regressor[app].predict(X_test) for app in app_cols]
overall_pred = pd.DataFrame(pred).transpose()
overall_pred = overall_pred.clip(lower=0)

In [11]:
def calculate_nilm_metrics(y_true, y_pred, appliance_names):
    y_t, y_p = np.array(y_true), np.array(y_pred)
    eps = 1e-9
    sum_min = np.minimum(y_p, y_t).sum(axis=0)
    sum_pred, sum_true = y_p.sum(axis=0), y_t.sum(axis=0)

    precision = sum_min / (sum_pred + eps)
    recall = sum_min / (sum_true + eps)
    f1 = 2 * precision * recall / (precision + recall + eps)
    abs_err = np.abs(y_t - y_p).sum(axis=0)
    nep = abs_err / (sum_true + eps)
    mae = abs_err / y_t.shape[0]

    out = pd.DataFrame({
        'Appliance': appliance_names,
        'Precision (PE)': precision.round(4),
        'Recall (RE)': recall.round(4),
        'F1-Score (FE)': f1.round(4),
        'NEP': nep.round(4),
        'MAE (W)': mae.round(4),
    })
    avg = ['--- AVERAGE ---'] + out.iloc[:, 1:].mean().round(4).tolist()
    out.loc[len(out)] = avg
    return out


metrics_table = calculate_nilm_metrics(
    y_test.reset_index(drop=True).drop(columns=['remain']), overall_pred, app_cols
)
print('XGBoost Regressor rating table:')
display(metrics_table)

XGBoost Regressor rating table:

,Appliance,Precision (PE),Recall (RE),F1-Score (FE),NEP,MAE (W)
0,Appliance1,0.6980,0.6571,0.6769,0.6272,21.416500
1,Appliance2,0.3900,0.4528,0.4190,1.2555,20.743999
2,Appliance3,0.7185,0.6619,0.6890,0.5974,38.756599
3,Appliance4,0.4072,0.2019,0.2699,1.0920,7.949500
4,Appliance5,0.4998,0.4910,0.4953,1.0004,3.561900
5,Appliance6,0.4271,0.5569,0.4835,1.1900,3.135100
6,Appliance7,0.0674,0.3149,0.1111,5.0399,3.496300
7,Appliance8,0.8776,0.8475,0.8623,0.2708,5.738300
8,Appliance9,0.0563,0.0638,0.0598,2.0071,0.414400
9,--- AVERAGE ---,0.4602,0.4720,0.4519,1.4534,11.690300