In [1]:
import sys
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb

base_dir = os.path.dirname(os.path.dirname(os.getcwd()))
data_dir = os.path.join(base_dir, 'data', 'processed_data', 'House2_full.csv')
sys.path.append(base_dir)

from src.tools.window_shifter import WindowShifter
from src.metrics.energy_base_metrics import MAE, NEP, Precision_energy_based, Recall_energy_based, F1_energy_based

In [5]:
df = pd.read_csv(data_dir, encoding = 'utf-8')
app_cols = ['Appliance1', 'Appliance2', 'Appliance3', 'Appliance4', 'Appliance5', 'Appliance6', 'Appliance7', 'Appliance8', 'Appliance9']
invalid_mask = df['Aggregate'] < df[app_cols].sum(axis=1)
df.loc[invalid_mask, app_cols] = np.nan
df[app_cols] = df[app_cols].interpolate(method='linear').bfill().ffill()
df.loc[invalid_mask, 'Aggregate'] = np.nan
df['Aggregate'] = df['Aggregate'].interpolate(method='linear').bfill().ffill()
df = WindowShifter.shift(df, 50)
aggregate_cols = [i for i in df.columns[:-9] if 'Time' not in i]
df['remain'] = df['Aggregate_t0'] - df[app_cols].sum(axis = 1)
df['remain'] = df['remain'].clip(lower=0)

In [6]:
df_time_to_date = pd.to_datetime(df['Time_t0'], format='%Y-%m-%d %H:%M:%S')
df['dow'] = df_time_to_date.dt.day_of_week
df['dom'] = df_time_to_date.dt.day
df['hour'] = df_time_to_date.dt.hour

In [7]:
df.head()

,Time_t0,Aggregate_t0,Time_t1,Aggregate_t1,Time_t2,Aggregate_t2,Time_t3,Aggregate_t3,Time_t4,Aggregate_t4,...,Appliance4,Appliance5,Appliance6,Appliance7,Appliance8,Appliance9,remain,dow,dom,hour
49,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,2013-09-17 22:13:24,702.0,2013-09-17 22:13:20,698.0,2013-09-17 22:13:17,696.0,...,0.0,0.0,0.0,0.0,0.0,0.0,609.0,1,17,22
50,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,2013-09-17 22:13:24,702.0,2013-09-17 22:13:20,698.0,...,0.0,0.0,0.0,0.0,0.0,0.0,597.0,1,17,22
51,2013-09-17 22:13:54,686.0,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,2013-09-17 22:13:24,702.0,...,0.0,0.0,0.0,0.0,0.0,0.0,601.0,1,17,22
52,2013-09-17 22:14:01,691.0,2013-09-17 22:13:54,686.0,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,...,0.0,0.0,0.0,0.0,0.0,0.0,606.0,1,17,22
53,2013-09-17 22:14:08,691.0,2013-09-17 22:14:01,691.0,2013-09-17 22:13:54,686.0,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,...,0.0,0.0,0.0,0.0,0.0,0.0,606.0,1,17,22

In [9]:
df[app_cols].describe()

,Appliance1,Appliance2,Appliance3,Appliance4,Appliance5,Appliance6,Appliance7,Appliance8,Appliance9
count,5.733477e+06,5.733477e+06,5.733477e+06,5.733477e+06,5.733477e+06,5.733477e+06,5.733477e+06,5.733477e+06,5.733477e+06
mean,3.562417e+01,1.803707e+01,6.058062e+01,3.951857e+00,2.810471e+00,1.449910e+00,1.728182e+00,2.198316e+01,3.663726e-01
std,4.353730e+01,1.734733e+02,3.487188e+02,1.260141e+01,5.320088e+01,3.633231e+01,5.080037e+00,2.407520e+02,5.080304e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,8.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.639000e+03,2.555000e+03,2.480000e+03,5.120000e+02,1.251000e+03,1.024000e+03,1.536000e+03,2.939000e+03,3.840000e+02

### Ý tưởng ###
* Tạo 2 model 1 model để xem liệu thiết bị có đang hoạt động không nếu thiết bị đang hoạt động thì dự đoán công suất của nó

In [10]:
on_threshold = {
    'Appliance1': 15,    # Fridge-Freezer: may nen chay ~50-150W
    'Appliance2': 20,    # Washing Machine: nhieu che do tu 20W
    'Appliance3': 20,    # Dishwasher: che do nhe tu 10W
    'Appliance4': 15,    # Television: xem TV 50-200W
    'Appliance5': 50,   # Microwave: cong suat cao, standby rat thap
    'Appliance6': 50,   # Toaster: cong suat cao, bat cuc ngan
    'Appliance7': 10,    # Hi-Fi: cong suat thap
    'Appliance8': 100,   # Kettle: cong suat rat cao 2000-3000W
    'Appliance9': 5,    # Oven Extractor Fan: quat hut
}

In [11]:
x_cols = ['dow', 'dom', 'hour'] + aggregate_cols
y_cols = app_cols + ['remain']

In [16]:
df_classifier = df.copy()
for i in app_cols:
    df_classifier[i] = df_classifier[i]<on_threshold[i]
df_classifier.head()

,Time_t0,Aggregate_t0,Time_t1,Aggregate_t1,Time_t2,Aggregate_t2,Time_t3,Aggregate_t3,Time_t4,Aggregate_t4,...,Appliance4,Appliance5,Appliance6,Appliance7,Appliance8,Appliance9,remain,dow,dom,hour
49,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,2013-09-17 22:13:24,702.0,2013-09-17 22:13:20,698.0,2013-09-17 22:13:17,696.0,...,True,True,True,True,True,True,609.0,1,17,22
50,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,2013-09-17 22:13:24,702.0,2013-09-17 22:13:20,698.0,...,True,True,True,True,True,True,597.0,1,17,22
51,2013-09-17 22:13:54,686.0,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,2013-09-17 22:13:24,702.0,...,True,True,True,True,True,True,601.0,1,17,22
52,2013-09-17 22:14:01,691.0,2013-09-17 22:13:54,686.0,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,2013-09-17 22:13:32,694.0,...,True,True,True,True,True,True,606.0,1,17,22
53,2013-09-17 22:14:08,691.0,2013-09-17 22:14:01,691.0,2013-09-17 22:13:54,686.0,2013-09-17 22:13:46,683.0,2013-09-17 22:13:39,695.0,...,True,True,True,True,True,True,606.0,1,17,22

In [29]:
from sklearn.model_selection import train_test_split
X_train_class, y_train_class = df_classifier[((df_classifier['dom']-1)//7+1)%2==0][x_cols], df_classifier[((df_classifier['dom']-1)//7+1)%2==0][y_cols]
X_train_class, X_val_class, y_train_class, y_val_class = train_test_split(X_train_class, y_train_class, test_size = 0.01)

In [36]:
df.loc[3953788][app_cols]

Appliance1     1.0
Appliance2     0.0
Appliance3     0.0
Appliance4    40.0
Appliance5     0.0
Appliance6     0.0
Appliance7     0.0
Appliance8     0.0
Appliance9     0.0
Name: 3953788, dtype: object

In [47]:
df.loc[3953788]['remain']

np.float64(10203.0)

In [51]:
app1_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app1_class.fit(X_train_class, y_train_class['Appliance1'],
    eval_set=[(X_val_class, y_val_class['Appliance1'])], 
    verbose=100)

app2_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app2_class.fit(X_train_class, y_train_class['Appliance2'],
    eval_set=[(X_val_class, y_val_class['Appliance2'])], 
    verbose=100)

app3_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app3_class.fit(X_train_class, y_train_class['Appliance3'],
    eval_set=[(X_val_class, y_val_class['Appliance3'])], 
    verbose=100)

app4_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app4_class.fit(X_train_class, y_train_class['Appliance4'],
    eval_set=[(X_val_class, y_val_class['Appliance4'])], 
    verbose=100)

app5_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app5_class.fit(X_train_class, y_train_class['Appliance5'],
    eval_set=[(X_val_class, y_val_class['Appliance5'])], 
    verbose=100)

app6_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app6_class.fit(X_train_class, y_train_class['Appliance6'],
    eval_set=[(X_val_class, y_val_class['Appliance6'])], 
    verbose=100)

app7_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app7_class.fit(X_train_class, y_train_class['Appliance7'],
    eval_set=[(X_val_class, y_val_class['Appliance7'])], 
    verbose=100)

app8_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app8_class.fit(X_train_class, y_train_class['Appliance8'],
    eval_set=[(X_val_class, y_val_class['Appliance8'])], 
    verbose=100)

app9_class = xgb.XGBClassifier(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
app9_class.fit(X_train_class, y_train_class['Appliance9'],
    eval_set=[(X_val_class, y_val_class['Appliance9'])], 
    verbose=100)

[0]	validation_0-logloss:0.65683
[100]	validation_0-logloss:0.36317
[200]	validation_0-logloss:0.33642
[300]	validation_0-logloss:0.31871
[400]	validation_0-logloss:0.30376
[500]	validation_0-logloss:0.29311
[600]	validation_0-logloss:0.28526
[700]	validation_0-logloss:0.27823
[800]	validation_0-logloss:0.27128
[900]	validation_0-logloss:0.26501
[1000]	validation_0-logloss:0.25928
[1100]	validation_0-logloss:0.25518
[1200]	validation_0-logloss:0.25049
[1300]	validation_0-logloss:0.24633
[1400]	validation_0-logloss:0.24278
[1500]	validation_0-logloss:0.23930
[1600]	validation_0-logloss:0.23501
[1700]	validation_0-logloss:0.23188
[1800]	validation_0-logloss:0.22875
[1900]	validation_0-logloss:0.22610
[2000]	validation_0-logloss:0.22384
[2100]	validation_0-logloss:0.22058
[2200]	validation_0-logloss:0.21688
[2300]	validation_0-logloss:0.21460
[2400]	validation_0-logloss:0.21196
[2500]	validation_0-logloss:0.20935
[2600]	validation_0-logloss:0.20717
[2700]	validation_0-logloss:0.20457
[2800]	validation_0-logloss:0.20230
[2900]	validation_0-logloss:0.20017
[3000]	validation_0-logloss:0.19835
[3100]	validation_0-logloss:0.19654
[3200]	validation_0-logloss:0.19508
[3300]	validation_0-logloss:0.19338
[3400]	validation_0-logloss:0.19219
[3500]	validation_0-logloss:0.19069
[3600]	validation_0-logloss:0.18928
[3700]	validation_0-logloss:0.18773
[3800]	validation_0-logloss:0.18569
[3900]	validation_0-logloss:0.18402
[4000]	validation_0-logloss:0.18228
[4100]	validation_0-logloss:0.18085
[4200]	validation_0-logloss:0.17913
[4300]	validation_0-logloss:0.17763
[4400]	validation_0-logloss:0.17595
[4500]	validation_0-logloss:0.17447
[4600]	validation_0-logloss:0.17344
[4700]	validation_0-logloss:0.17213
[4800]	validation_0-logloss:0.17079
[4900]	validation_0-logloss:0.16899
[4999]	validation_0-logloss:0.16758
[0]	validation_0-logloss:0.14795
[100]	validation_0-logloss:0.07983
[200]	validation_0-logloss:0.06430
[300]	validation_0-logloss:0.05699
[400]	validation_0-logloss:0.05220
[500]	validation_0-logloss:0.04830
[600]	validation_0-logloss:0.04464
[700]	validation_0-logloss:0.04243
[800]	validation_0-logloss:0.04084
[900]	validation_0-logloss:0.03938
[1000]	validation_0-logloss:0.03768
[1100]	validation_0-logloss:0.03645
[1200]	validation_0-logloss:0.03541
[1300]	validation_0-logloss:0.03465
[1400]	validation_0-logloss:0.03390
[1500]	validation_0-logloss:0.03354
[1600]	validation_0-logloss:0.03288
[1700]	validation_0-logloss:0.03224
[1800]	validation_0-logloss:0.03166
[1900]	validation_0-logloss:0.03121
[2000]	validation_0-logloss:0.03087
[2100]	validation_0-logloss:0.03046
[2200]	validation_0-logloss:0.03004
[2300]	validation_0-logloss:0.02965
[2400]	validation_0-logloss:0.02944
[2500]	validation_0-logloss:0.02918
[2600]	validation_0-logloss:0.02902
[2700]	validation_0-logloss:0.02887
[2800]	validation_0-logloss:0.02866
[2900]	validation_0-logloss:0.02847
[3000]	validation_0-logloss:0.02827
[3100]	validation_0-logloss:0.02804
[3200]	validation_0-logloss:0.02789
[3300]	validation_0-logloss:0.02777
[3400]	validation_0-logloss:0.02759
[3500]	validation_0-logloss:0.02747
[3600]	validation_0-logloss:0.02729
[3700]	validation_0-logloss:0.02716
[3800]	validation_0-logloss:0.02711
[3900]	validation_0-logloss:0.02704
[4000]	validation_0-logloss:0.02696
[4100]	validation_0-logloss:0.02685
[4200]	validation_0-logloss:0.02672
[4300]	validation_0-logloss:0.02664
[4400]	validation_0-logloss:0.02651
[4500]	validation_0-logloss:0.02639
[4600]	validation_0-logloss:0.02630
[4700]	validation_0-logloss:0.02613
[4800]	validation_0-logloss:0.02608
[4900]	validation_0-logloss:0.02598
[4999]	validation_0-logloss:0.02590
[0]	validation_0-logloss:0.25958
[100]	validation_0-logloss:0.15141
[200]	validation_0-logloss:0.13326
[300]	validation_0-logloss:0.12126
[400]	validation_0-logloss:0.11236
[500]	validation_0-logloss:0.10595
[600]	validation_0-logloss:0.09956
[700]	validation_0-logloss:0.09504
[800]	validation_0-logloss:0.08954
[900]	validation_0-logloss:0.08679
[1000]	validation_0-logloss:0.08358
[1100]	validation_0-logloss:0.08070
[1200]	validation_0-logloss:0.07795
[1300]	validation_0-logloss:0.07565
[1400]	validation_0-logloss:0.07296
[1500]	validation_0-logloss:0.07052
[1600]	validation_0-logloss:0.06896
[1700]	validation_0-logloss:0.06696
[1800]	validation_0-logloss:0.06511
[1900]	validation_0-logloss:0.06351
[2000]	validation_0-logloss:0.06205
[2100]	validation_0-logloss:0.06050
[2200]	validation_0-logloss:0.05909
[2300]	validation_0-logloss:0.05736
[2400]	validation_0-logloss:0.05614
[2500]	validation_0-logloss:0.05475
[2600]	validation_0-logloss:0.05382
[2700]	validation_0-logloss:0.05219
[2800]	validation_0-logloss:0.05114
[2900]	validation_0-logloss:0.05044
[3000]	validation_0-logloss:0.04953
[3100]	validation_0-logloss:0.04865
[3200]	validation_0-logloss:0.04788
[3300]	validation_0-logloss:0.04728
[3400]	validation_0-logloss:0.04631
[3500]	validation_0-logloss:0.04527
[3600]	validation_0-logloss:0.04419
[3700]	validation_0-logloss:0.04316
[3800]	validation_0-logloss:0.04245
[3900]	validation_0-logloss:0.04187
[4000]	validation_0-logloss:0.04137
[4100]	validation_0-logloss:0.04075
[4200]	validation_0-logloss:0.04000
[4300]	validation_0-logloss:0.03935
[4400]	validation_0-logloss:0.03871
[4500]	validation_0-logloss:0.03802
[4600]	validation_0-logloss:0.03750
[4700]	validation_0-logloss:0.03706
[4800]	validation_0-logloss:0.03652
[4900]	validation_0-logloss:0.03583
[4999]	validation_0-logloss:0.03513
[0]	validation_0-logloss:0.30860
[100]	validation_0-logloss:0.20405
[200]	validation_0-logloss:0.18142
[300]	validation_0-logloss:0.16690
[400]	validation_0-logloss:0.15680
[500]	validation_0-logloss:0.14819
[600]	validation_0-logloss:0.13999
[700]	validation_0-logloss:0.13498
[800]	validation_0-logloss:0.12911
[900]	validation_0-logloss:0.12541
[1000]	validation_0-logloss:0.12183
[1100]	validation_0-logloss:0.11752
[1200]	validation_0-logloss:0.11417
[1300]	validation_0-logloss:0.11117
[1400]	validation_0-logloss:0.10705
[1500]	validation_0-logloss:0.10424
[1600]	validation_0-logloss:0.10132
[1700]	validation_0-logloss:0.09832
[1800]	validation_0-logloss:0.09602
[1900]	validation_0-logloss:0.09382
[2000]	validation_0-logloss:0.09179
[2100]	validation_0-logloss:0.08940
[2200]	validation_0-logloss:0.08701
[2300]	validation_0-logloss:0.08540
[2400]	validation_0-logloss:0.08424
[2500]	validation_0-logloss:0.08321
[2600]	validation_0-logloss:0.08113
[2700]	validation_0-logloss:0.07933
[2800]	validation_0-logloss:0.07784
[2900]	validation_0-logloss:0.07662
[3000]	validation_0-logloss:0.07514
[3100]	validation_0-logloss:0.07370
[3200]	validation_0-logloss:0.07271
[3300]	validation_0-logloss:0.07122
[3400]	validation_0-logloss:0.06986
[3500]	validation_0-logloss:0.06881
[3600]	validation_0-logloss:0.06756
[3700]	validation_0-logloss:0.06650
[3800]	validation_0-logloss:0.06508
[3900]	validation_0-logloss:0.06397
[4000]	validation_0-logloss:0.06272
[4100]	validation_0-logloss:0.06195
[4200]	validation_0-logloss:0.06104
[4300]	validation_0-logloss:0.06010
[4400]	validation_0-logloss:0.05920
[4500]	validation_0-logloss:0.05827
[4600]	validation_0-logloss:0.05732
[4700]	validation_0-logloss:0.05631
[4800]	validation_0-logloss:0.05549
[4900]	validation_0-logloss:0.05446
[4999]	validation_0-logloss:0.05385
[0]	validation_0-logloss:0.01353
[100]	validation_0-logloss:0.00544
[200]	validation_0-logloss:0.00465
[300]	validation_0-logloss:0.00409
[400]	validation_0-logloss:0.00366
[500]	validation_0-logloss:0.00337
[600]	validation_0-logloss:0.00317
[700]	validation_0-logloss:0.00295
[800]	validation_0-logloss:0.00276
[900]	validation_0-logloss:0.00261
[1000]	validation_0-logloss:0.00250
[1100]	validation_0-logloss:0.00240
[1200]	validation_0-logloss:0.00232
[1300]	validation_0-logloss:0.00225
[1400]	validation_0-logloss:0.00220
[1500]	validation_0-logloss:0.00218
[1600]	validation_0-logloss:0.00213
[1700]	validation_0-logloss:0.00210
[1800]	validation_0-logloss:0.00207
[1900]	validation_0-logloss:0.00202
[2000]	validation_0-logloss:0.00199
[2100]	validation_0-logloss:0.00198
[2200]	validation_0-logloss:0.00195
[2300]	validation_0-logloss:0.00192
[2400]	validation_0-logloss:0.00190
[2500]	validation_0-logloss:0.00189
[2600]	validation_0-logloss:0.00186
[2700]	validation_0-logloss:0.00183
[2800]	validation_0-logloss:0.00181
[2836]	validation_0-logloss:0.00181
[0]	validation_0-logloss:0.00836
[100]	validation_0-logloss:0.00351
[200]	validation_0-logloss:0.00296
[300]	validation_0-logloss:0.00254
[400]	validation_0-logloss:0.00226
[500]	validation_0-logloss:0.00208
[600]	validation_0-logloss:0.00201
[700]	validation_0-logloss:0.00196
[800]	validation_0-logloss:0.00190
[900]	validation_0-logloss:0.00188
[1000]	validation_0-logloss:0.00182
[1068]	validation_0-logloss:0.00182
[0]	validation_0-logloss:0.33623
[100]	validation_0-logloss:0.20620
[200]	validation_0-logloss:0.16351
[300]	validation_0-logloss:0.14434
[400]	validation_0-logloss:0.13234
[500]	validation_0-logloss:0.12256
[600]	validation_0-logloss:0.10990
[700]	validation_0-logloss:0.09792
[800]	validation_0-logloss:0.08967
[900]	validation_0-logloss:0.08193
[1000]	validation_0-logloss:0.07653
[1100]	validation_0-logloss:0.07258
[1200]	validation_0-logloss:0.06931
[1300]	validation_0-logloss:0.06630
[1400]	validation_0-logloss:0.06300
[1500]	validation_0-logloss:0.06056
[1600]	validation_0-logloss:0.05808
[1700]	validation_0-logloss:0.05544
[1800]	validation_0-logloss:0.05348
[1900]	validation_0-logloss:0.05132
[2000]	validation_0-logloss:0.04983
[2100]	validation_0-logloss:0.04825
[2200]	validation_0-logloss:0.04651
[2300]	validation_0-logloss:0.04483
[2400]	validation_0-logloss:0.04300
[2500]	validation_0-logloss:0.04161
[2600]	validation_0-logloss:0.04047
[2700]	validation_0-logloss:0.03954
[2800]	validation_0-logloss:0.03858
[2900]	validation_0-logloss:0.03711
[3000]	validation_0-logloss:0.03601
[3100]	validation_0-logloss:0.03511
[3200]	validation_0-logloss:0.03391
[3300]	validation_0-logloss:0.03286
[3400]	validation_0-logloss:0.03213
[3500]	validation_0-logloss:0.03123
[3600]	validation_0-logloss:0.03032
[3700]	validation_0-logloss:0.02958
[3800]	validation_0-logloss:0.02908
[3900]	validation_0-logloss:0.02857
[4000]	validation_0-logloss:0.02760
[4100]	validation_0-logloss:0.02686
[4200]	validation_0-logloss:0.02621
[4300]	validation_0-logloss:0.02550
[4400]	validation_0-logloss:0.02500
[4500]	validation_0-logloss:0.02472
[4600]	validation_0-logloss:0.02402
[4700]	validation_0-logloss:0.02357
[4800]	validation_0-logloss:0.02292
[4900]	validation_0-logloss:0.02261
[4999]	validation_0-logloss:0.02218
[0]	validation_0-logloss:0.02276
[100]	validation_0-logloss:0.00616
[200]	validation_0-logloss:0.00542
[300]	validation_0-logloss:0.00485
[400]	validation_0-logloss:0.00436
[500]	validation_0-logloss:0.00407
[600]	validation_0-logloss:0.00389
[700]	validation_0-logloss:0.00374
[800]	validation_0-logloss:0.00364
[900]	validation_0-logloss:0.00349
[1000]	validation_0-logloss:0.00338
[1100]	validation_0-logloss:0.00330
[1200]	validation_0-logloss:0.00324
[1300]	validation_0-logloss:0.00316
[1400]	validation_0-logloss:0.00310
[1500]	validation_0-logloss:0.00306
[1600]	validation_0-logloss:0.00302
[1700]	validation_0-logloss:0.00296
[1800]	validation_0-logloss:0.00292
[1900]	validation_0-logloss:0.00289
[2000]	validation_0-logloss:0.00285
[2100]	validation_0-logloss:0.00282
[2198]	validation_0-logloss:0.00280
[0]	validation_0-logloss:0.03875
[100]	validation_0-logloss:0.01772
[200]	validation_0-logloss:0.01256
[300]	validation_0-logloss:0.01000
[400]	validation_0-logloss:0.00805
[500]	validation_0-logloss:0.00672
[600]	validation_0-logloss:0.00577
[700]	validation_0-logloss:0.00500
[800]	validation_0-logloss:0.00433
[900]	validation_0-logloss:0.00385
[1000]	validation_0-logloss:0.00343
[1100]	validation_0-logloss:0.00311
[1200]	validation_0-logloss:0.00275
[1300]	validation_0-logloss:0.00248
[1400]	validation_0-logloss:0.00223
[1500]	validation_0-logloss:0.00207
[1600]	validation_0-logloss:0.00190
[1700]	validation_0-logloss:0.00178
[1800]	validation_0-logloss:0.00164
[1900]	validation_0-logloss:0.00157
[2000]	validation_0-logloss:0.00148
[2100]	validation_0-logloss:0.00140
[2200]	validation_0-logloss:0.00132
[2300]	validation_0-logloss:0.00127
[2400]	validation_0-logloss:0.00121
[2500]	validation_0-logloss:0.00116
[2600]	validation_0-logloss:0.00112
[2700]	validation_0-logloss:0.00108
[2800]	validation_0-logloss:0.00104
[2900]	validation_0-logloss:0.00101
[3000]	validation_0-logloss:0.00098
[3100]	validation_0-logloss:0.00097
[3200]	validation_0-logloss:0.00095
[3300]	validation_0-logloss:0.00094
[3400]	validation_0-logloss:0.00092
[3500]	validation_0-logloss:0.00091
[3600]	validation_0-logloss:0.00090
[3700]	validation_0-logloss:0.00088
[3800]	validation_0-logloss:0.00086
[3900]	validation_0-logloss:0.00085
[3926]	validation_0-logloss:0.00085

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cuda', early_stopping_rounds=50,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=5000,
              n_jobs=None, num_parallel_tree=None, ...)

In [52]:
X_test_class, y_test_class = df_classifier[((df_classifier['dom']-1)//7+1)%2==1][x_cols], df_classifier[((df_classifier['dom']-1)//7+1)%2==1][y_cols]

In [66]:
from sklearn.metrics import recall_score, precision_score, f1_score, confusion_matrix
f1_score(app1_class.predict(X_test_class), y_test_class['Appliance1'])

0.8420683940882188

In [67]:
f1_score(app2_class.predict(X_test_class), y_test_class['Appliance2'])

0.9837038039609947

In [68]:
f1_score(app3_class.predict(X_test_class), y_test_class['Appliance3'])

0.957349553847406

In [69]:
f1_score(app4_class.predict(X_test_class), y_test_class['Appliance4'])

0.9447709381619954

In [70]:
f1_score(app5_class.predict(X_test_class), y_test_class['Appliance5'])

0.9990212673745059

In [71]:
f1_score(app6_class.predict(X_test_class), y_test_class['Appliance6'])

0.9994341690537486

In [72]:
f1_score(app7_class.predict(X_test_class), y_test_class['Appliance7'])

0.9066264188254787

In [73]:
f1_score(app8_class.predict(X_test_class), y_test_class['Appliance8'])

0.9987439092525638

In [74]:
f1_score(app9_class.predict(X_test_class), y_test_class['Appliance9'])

0.9974003092913981

In [75]:
X_train, y_train, X_test, y_test = df[((df['dom']-1)//7+1)%2==0][x_cols], df[((df['dom']-1)//7+1)%2==0][y_cols], df[((df['dom']-1)//7+1)%2==1][x_cols], df[((df['dom']-1)//7+1)%2==1][y_cols]
X_test = X_test[:70000]
y_test = y_test[:70000]

In [76]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.05)

In [80]:
classifier = {
    'Appliance1': app1_class,
    'Appliance2': app2_class,
    'Appliance3': app3_class,
    'Appliance4': app4_class,
    'Appliance5': app5_class,
    'Appliance6': app6_class,
    'Appliance7': app7_class,
    'Appliance8': app8_class,
    'Appliance9': app9_class
}

In [78]:
regressor = {}

In [86]:
for app in app_cols:
    model = xgb.XGBRegressor(n_estimators=5000,      
    learning_rate=0.05,
    early_stopping_rounds=50, 
    tree_method='hist',      
    device="cuda")
    model.fit(X_train, y_train[app], eval_set=[(X_val, y_val[app])], verbose=100)
    regressor[app] = model

[0]	validation_0-rmse:43.05305
[100]	validation_0-rmse:31.92725
[200]	validation_0-rmse:30.58624
[300]	validation_0-rmse:29.87585
[400]	validation_0-rmse:29.27717
[500]	validation_0-rmse:28.80916
[600]	validation_0-rmse:28.37066
[700]	validation_0-rmse:28.00750
[800]	validation_0-rmse:27.73262
[900]	validation_0-rmse:27.45614
[1000]	validation_0-rmse:27.17491
[1100]	validation_0-rmse:26.98730
[1200]	validation_0-rmse:26.74218
[1300]	validation_0-rmse:26.57300
[1400]	validation_0-rmse:26.37680
[1500]	validation_0-rmse:26.12608
[1600]	validation_0-rmse:25.93647
[1700]	validation_0-rmse:25.75547
[1800]	validation_0-rmse:25.56315
[1900]	validation_0-rmse:25.39690
[2000]	validation_0-rmse:25.29172
[2100]	validation_0-rmse:25.15685
[2200]	validation_0-rmse:25.01523
[2300]	validation_0-rmse:24.84418
[2400]	validation_0-rmse:24.74371
[2500]	validation_0-rmse:24.59922
[2600]	validation_0-rmse:24.43812
[2700]	validation_0-rmse:24.32739
[2800]	validation_0-rmse:24.21107
[2900]	validation_0-rmse:24.07266
[3000]	validation_0-rmse:23.96119
[3100]	validation_0-rmse:23.85496
[3200]	validation_0-rmse:23.76964
[3300]	validation_0-rmse:23.66644
[3400]	validation_0-rmse:23.57583
[3500]	validation_0-rmse:23.49451
[3600]	validation_0-rmse:23.40568
[3700]	validation_0-rmse:23.31549
[3800]	validation_0-rmse:23.23568
[3900]	validation_0-rmse:23.15542
[4000]	validation_0-rmse:23.06300
[4100]	validation_0-rmse:22.95447
[4200]	validation_0-rmse:22.85540
[4300]	validation_0-rmse:22.77957
[4400]	validation_0-rmse:22.68569
[4500]	validation_0-rmse:22.60517
[4600]	validation_0-rmse:22.54316
[4700]	validation_0-rmse:22.46085
[4800]	validation_0-rmse:22.39291
[4900]	validation_0-rmse:22.30949
[4999]	validation_0-rmse:22.24555
[0]	validation_0-rmse:173.03780
[100]	validation_0-rmse:125.49456
[200]	validation_0-rmse:112.18834
[300]	validation_0-rmse:104.32936
[400]	validation_0-rmse:100.39602
[500]	validation_0-rmse:97.14270
[600]	validation_0-rmse:93.78290
[700]	validation_0-rmse:90.80747
[800]	validation_0-rmse:88.38884
[900]	validation_0-rmse:86.66022
[1000]	validation_0-rmse:85.12021
[1100]	validation_0-rmse:83.58385
[1200]	validation_0-rmse:82.50713
[1300]	validation_0-rmse:81.14924
[1400]	validation_0-rmse:79.71231
[1500]	validation_0-rmse:78.66631
[1600]	validation_0-rmse:77.71486
[1700]	validation_0-rmse:76.83240
[1800]	validation_0-rmse:76.14707
[1900]	validation_0-rmse:75.08424
[2000]	validation_0-rmse:74.16947
[2100]	validation_0-rmse:73.55584
[2200]	validation_0-rmse:73.05318
[2300]	validation_0-rmse:72.59715
[2400]	validation_0-rmse:72.15557
[2500]	validation_0-rmse:71.61390
[2600]	validation_0-rmse:71.04869
[2700]	validation_0-rmse:70.48793
[2800]	validation_0-rmse:69.97032
[2900]	validation_0-rmse:69.48202
[3000]	validation_0-rmse:69.00988
[3100]	validation_0-rmse:68.37335
[3200]	validation_0-rmse:67.69064
[3300]	validation_0-rmse:67.36348
[3400]	validation_0-rmse:67.03742
[3500]	validation_0-rmse:66.70044
[3600]	validation_0-rmse:66.43668
[3700]	validation_0-rmse:66.20668
[3800]	validation_0-rmse:65.86139
[3900]	validation_0-rmse:65.49849
[4000]	validation_0-rmse:65.13885
[4100]	validation_0-rmse:64.88683
[4200]	validation_0-rmse:64.61085
[4300]	validation_0-rmse:64.34532
[4400]	validation_0-rmse:64.10676
[4500]	validation_0-rmse:63.88120
[4600]	validation_0-rmse:63.66507
[4700]	validation_0-rmse:63.46451
[4800]	validation_0-rmse:63.25831
[4900]	validation_0-rmse:63.02060
[4999]	validation_0-rmse:62.71746
[0]	validation_0-rmse:330.23643
[100]	validation_0-rmse:179.34231
[200]	validation_0-rmse:163.24410
[300]	validation_0-rmse:153.52190
[400]	validation_0-rmse:146.49981
[500]	validation_0-rmse:140.58226
[600]	validation_0-rmse:135.45641
[700]	validation_0-rmse:131.30313
[800]	validation_0-rmse:127.97998
[900]	validation_0-rmse:124.57623
[1000]	validation_0-rmse:121.62439
[1100]	validation_0-rmse:118.48272
[1200]	validation_0-rmse:116.18204
[1300]	validation_0-rmse:113.79697
[1400]	validation_0-rmse:111.93908
[1500]	validation_0-rmse:110.27369
[1600]	validation_0-rmse:109.14166
[1700]	validation_0-rmse:107.73182
[1800]	validation_0-rmse:106.32904
[1900]	validation_0-rmse:104.62408
[2000]	validation_0-rmse:103.42347
[2100]	validation_0-rmse:102.36121
[2200]	validation_0-rmse:101.31136
[2300]	validation_0-rmse:100.37248
[2400]	validation_0-rmse:99.59962
[2500]	validation_0-rmse:98.81656
[2600]	validation_0-rmse:98.32334
[2700]	validation_0-rmse:97.82036
[2800]	validation_0-rmse:97.10420
[2900]	validation_0-rmse:96.45365
[3000]	validation_0-rmse:95.94503
[3100]	validation_0-rmse:95.28154
[3200]	validation_0-rmse:94.73023
[3300]	validation_0-rmse:94.16655
[3400]	validation_0-rmse:93.40231
[3500]	validation_0-rmse:92.81744
[3600]	validation_0-rmse:92.40963
[3700]	validation_0-rmse:91.88149
[3800]	validation_0-rmse:91.31587
[3900]	validation_0-rmse:90.68937
[4000]	validation_0-rmse:90.28535
[4100]	validation_0-rmse:89.85517
[4200]	validation_0-rmse:89.52280
[4300]	validation_0-rmse:89.08519
[4400]	validation_0-rmse:88.81274
[4500]	validation_0-rmse:88.56175
[4600]	validation_0-rmse:88.16493
[4700]	validation_0-rmse:87.73586
[4800]	validation_0-rmse:87.32105
[4900]	validation_0-rmse:87.02643
[4999]	validation_0-rmse:86.75995
[0]	validation_0-rmse:12.82036
[100]	validation_0-rmse:10.62343
[200]	validation_0-rmse:10.15207
[300]	validation_0-rmse:9.86148
[400]	validation_0-rmse:9.67248
[500]	validation_0-rmse:9.50438
[600]	validation_0-rmse:9.35313
[700]	validation_0-rmse:9.24464
[800]	validation_0-rmse:9.14310
[900]	validation_0-rmse:9.03456
[1000]	validation_0-rmse:8.93030
[1100]	validation_0-rmse:8.80943
[1200]	validation_0-rmse:8.72883
[1300]	validation_0-rmse:8.61664
[1400]	validation_0-rmse:8.53425
[1500]	validation_0-rmse:8.43996
[1600]	validation_0-rmse:8.37762
[1700]	validation_0-rmse:8.32042
[1800]	validation_0-rmse:8.25984
[1900]	validation_0-rmse:8.18147
[2000]	validation_0-rmse:8.11056
[2100]	validation_0-rmse:8.05721
[2200]	validation_0-rmse:7.99275
[2300]	validation_0-rmse:7.94290
[2400]	validation_0-rmse:7.88299
[2500]	validation_0-rmse:7.84342
[2600]	validation_0-rmse:7.77869
[2700]	validation_0-rmse:7.74821
[2800]	validation_0-rmse:7.69754
[2900]	validation_0-rmse:7.66291
[3000]	validation_0-rmse:7.62037
[3100]	validation_0-rmse:7.57422
[3200]	validation_0-rmse:7.52250
[3300]	validation_0-rmse:7.48985
[3400]	validation_0-rmse:7.44276
[3500]	validation_0-rmse:7.40942
[3600]	validation_0-rmse:7.37568
[3700]	validation_0-rmse:7.34595
[3800]	validation_0-rmse:7.29823
[3900]	validation_0-rmse:7.25133
[4000]	validation_0-rmse:7.22445
[4100]	validation_0-rmse:7.18967
[4200]	validation_0-rmse:7.15378
[4300]	validation_0-rmse:7.11554
[4400]	validation_0-rmse:7.08344
[4500]	validation_0-rmse:7.06058
[4600]	validation_0-rmse:7.03031
[4700]	validation_0-rmse:7.00854
[4800]	validation_0-rmse:6.98717
[4900]	validation_0-rmse:6.95105
[4999]	validation_0-rmse:6.92444
[0]	validation_0-rmse:55.01278
[100]	validation_0-rmse:40.94327
[200]	validation_0-rmse:38.85958
[300]	validation_0-rmse:37.65978
[400]	validation_0-rmse:36.78635
[500]	validation_0-rmse:36.23158
[600]	validation_0-rmse:35.53350
[700]	validation_0-rmse:35.09776
[800]	validation_0-rmse:34.67038
[900]	validation_0-rmse:34.26324
[1000]	validation_0-rmse:34.04818
[1100]	validation_0-rmse:33.72184
[1200]	validation_0-rmse:33.46432
[1300]	validation_0-rmse:33.16876
[1400]	validation_0-rmse:32.93613
[1500]	validation_0-rmse:32.73391
[1600]	validation_0-rmse:32.62592
[1700]	validation_0-rmse:32.46775
[1800]	validation_0-rmse:32.35166
[1900]	validation_0-rmse:32.21980
[2000]	validation_0-rmse:32.07951
[2100]	validation_0-rmse:31.99649
[2200]	validation_0-rmse:31.84492
[2300]	validation_0-rmse:31.74077
[2400]	validation_0-rmse:31.66072
[2500]	validation_0-rmse:31.54389
[2600]	validation_0-rmse:31.44349
[2700]	validation_0-rmse:31.36694
[2800]	validation_0-rmse:31.29738
[2900]	validation_0-rmse:31.21017
[3000]	validation_0-rmse:31.17366
[3100]	validation_0-rmse:31.09776
[3200]	validation_0-rmse:31.01462
[3300]	validation_0-rmse:30.97969
[3400]	validation_0-rmse:30.93608
[3500]	validation_0-rmse:30.87040
[3600]	validation_0-rmse:30.79879
[3700]	validation_0-rmse:30.75966
[3800]	validation_0-rmse:30.72277
[3900]	validation_0-rmse:30.67940
[4000]	validation_0-rmse:30.62009
[4100]	validation_0-rmse:30.58696
[4200]	validation_0-rmse:30.52475
[4300]	validation_0-rmse:30.46914
[4400]	validation_0-rmse:30.43874
[4500]	validation_0-rmse:30.40107
[4600]	validation_0-rmse:30.35252
[4700]	validation_0-rmse:30.33443
[4734]	validation_0-rmse:30.33442
[0]	validation_0-rmse:35.94341
[100]	validation_0-rmse:23.17654
[200]	validation_0-rmse:20.99133
[300]	validation_0-rmse:19.50640
[400]	validation_0-rmse:18.37786
[500]	validation_0-rmse:17.74384
[600]	validation_0-rmse:17.32405
[700]	validation_0-rmse:16.86938
[800]	validation_0-rmse:16.46884
[900]	validation_0-rmse:16.17229
[1000]	validation_0-rmse:15.92780
[1100]	validation_0-rmse:15.69619
[1200]	validation_0-rmse:15.52932
[1300]	validation_0-rmse:15.32678
[1400]	validation_0-rmse:15.09205
[1500]	validation_0-rmse:14.93493
[1600]	validation_0-rmse:14.78945
[1700]	validation_0-rmse:14.65355
[1800]	validation_0-rmse:14.49044
[1900]	validation_0-rmse:14.35274
[2000]	validation_0-rmse:14.23050
[2100]	validation_0-rmse:14.14301
[2200]	validation_0-rmse:14.02889
[2300]	validation_0-rmse:13.97721
[2400]	validation_0-rmse:13.89310
[2500]	validation_0-rmse:13.82463
[2600]	validation_0-rmse:13.74019
[2700]	validation_0-rmse:13.69030
[2800]	validation_0-rmse:13.64136
[2900]	validation_0-rmse:13.60130
[3000]	validation_0-rmse:13.56866
[3100]	validation_0-rmse:13.52668
[3200]	validation_0-rmse:13.48216
[3300]	validation_0-rmse:13.43363
[3400]	validation_0-rmse:13.41087
[3500]	validation_0-rmse:13.37406
[3600]	validation_0-rmse:13.33845
[3700]	validation_0-rmse:13.30135
[3800]	validation_0-rmse:13.25838
[3900]	validation_0-rmse:13.23673
[4000]	validation_0-rmse:13.21560
[4100]	validation_0-rmse:13.18858
[4200]	validation_0-rmse:13.16015
[4300]	validation_0-rmse:13.13662
[4400]	validation_0-rmse:13.11492
[4500]	validation_0-rmse:13.09432
[4600]	validation_0-rmse:13.05417
[4700]	validation_0-rmse:13.03962
[4800]	validation_0-rmse:13.01309
[4900]	validation_0-rmse:12.99385
[4999]	validation_0-rmse:12.97501
[0]	validation_0-rmse:4.96362
[100]	validation_0-rmse:3.95253
[200]	validation_0-rmse:3.61490
[300]	validation_0-rmse:3.40256
[400]	validation_0-rmse:3.26376
[500]	validation_0-rmse:3.16495
[600]	validation_0-rmse:3.06532
[700]	validation_0-rmse:2.99334
[800]	validation_0-rmse:2.92495
[900]	validation_0-rmse:2.87371
[1000]	validation_0-rmse:2.82424
[1100]	validation_0-rmse:2.79207
[1200]	validation_0-rmse:2.74161
[1300]	validation_0-rmse:2.71325
[1400]	validation_0-rmse:2.67916
[1500]	validation_0-rmse:2.64927
[1600]	validation_0-rmse:2.61324
[1700]	validation_0-rmse:2.58465
[1800]	validation_0-rmse:2.56787
[1900]	validation_0-rmse:2.54388
[2000]	validation_0-rmse:2.52135
[2100]	validation_0-rmse:2.49412
[2200]	validation_0-rmse:2.46957
[2300]	validation_0-rmse:2.44337
[2400]	validation_0-rmse:2.42067
[2500]	validation_0-rmse:2.40294
[2600]	validation_0-rmse:2.38837
[2700]	validation_0-rmse:2.37044
[2800]	validation_0-rmse:2.35999
[2900]	validation_0-rmse:2.34505
[3000]	validation_0-rmse:2.32745
[3100]	validation_0-rmse:2.31111
[3200]	validation_0-rmse:2.29336
[3300]	validation_0-rmse:2.28585
[3400]	validation_0-rmse:2.27781
[3500]	validation_0-rmse:2.26347
[3600]	validation_0-rmse:2.25033
[3700]	validation_0-rmse:2.24001
[3800]	validation_0-rmse:2.22716
[3900]	validation_0-rmse:2.21676
[4000]	validation_0-rmse:2.20726
[4100]	validation_0-rmse:2.19380
[4200]	validation_0-rmse:2.17955
[4300]	validation_0-rmse:2.16479
[4400]	validation_0-rmse:2.15161
[4500]	validation_0-rmse:2.14194
[4600]	validation_0-rmse:2.13372
[4700]	validation_0-rmse:2.12421
[4800]	validation_0-rmse:2.11561
[4900]	validation_0-rmse:2.10326
[4999]	validation_0-rmse:2.09582
[0]	validation_0-rmse:235.48333
[100]	validation_0-rmse:106.56622
[200]	validation_0-rmse:101.39167
[300]	validation_0-rmse:97.97524
[400]	validation_0-rmse:94.95887
[500]	validation_0-rmse:92.84849
[600]	validation_0-rmse:90.94857
[700]	validation_0-rmse:89.46349
[800]	validation_0-rmse:87.79512
[900]	validation_0-rmse:86.80848
[1000]	validation_0-rmse:85.64380
[1100]	validation_0-rmse:84.77110
[1200]	validation_0-rmse:84.21300
[1300]	validation_0-rmse:83.55007
[1400]	validation_0-rmse:83.03721
[1500]	validation_0-rmse:82.56052
[1600]	validation_0-rmse:82.06598
[1700]	validation_0-rmse:81.71074
[1800]	validation_0-rmse:81.23231
[1900]	validation_0-rmse:80.80623
[2000]	validation_0-rmse:80.35762
[2100]	validation_0-rmse:80.10345
[2200]	validation_0-rmse:79.68222
[2300]	validation_0-rmse:79.36111
[2400]	validation_0-rmse:79.07247
[2500]	validation_0-rmse:78.80622
[2600]	validation_0-rmse:78.56428
[2700]	validation_0-rmse:78.32495
[2800]	validation_0-rmse:78.12208
[2900]	validation_0-rmse:77.96207
[3000]	validation_0-rmse:77.84601
[3100]	validation_0-rmse:77.67794
[3200]	validation_0-rmse:77.43082
[3300]	validation_0-rmse:77.20130
[3400]	validation_0-rmse:76.99287
[3500]	validation_0-rmse:76.84371
[3600]	validation_0-rmse:76.67786
[3700]	validation_0-rmse:76.53470
[3800]	validation_0-rmse:76.41841
[3900]	validation_0-rmse:76.25858
[4000]	validation_0-rmse:76.09536
[4100]	validation_0-rmse:75.97557
[4200]	validation_0-rmse:75.87041
[4300]	validation_0-rmse:75.72481
[4400]	validation_0-rmse:75.66182
[4500]	validation_0-rmse:75.54551
[4600]	validation_0-rmse:75.46307
[4700]	validation_0-rmse:75.37461
[4800]	validation_0-rmse:75.27962
[4900]	validation_0-rmse:75.21668
[4999]	validation_0-rmse:75.13279
[0]	validation_0-rmse:5.84045
[100]	validation_0-rmse:4.76108
[200]	validation_0-rmse:4.42608
[300]	validation_0-rmse:4.25186
[400]	validation_0-rmse:4.10703
[500]	validation_0-rmse:3.97691
[600]	validation_0-rmse:3.89236
[700]	validation_0-rmse:3.80353
[800]	validation_0-rmse:3.73634
[900]	validation_0-rmse:3.67724
[1000]	validation_0-rmse:3.62126
[1100]	validation_0-rmse:3.56778
[1200]	validation_0-rmse:3.50825
[1300]	validation_0-rmse:3.45656
[1400]	validation_0-rmse:3.42530
[1500]	validation_0-rmse:3.39000
[1600]	validation_0-rmse:3.34550
[1700]	validation_0-rmse:3.31839
[1800]	validation_0-rmse:3.26444
[1900]	validation_0-rmse:3.23724
[2000]	validation_0-rmse:3.21127
[2100]	validation_0-rmse:3.18243
[2200]	validation_0-rmse:3.15601
[2300]	validation_0-rmse:3.12970
[2400]	validation_0-rmse:3.11000
[2500]	validation_0-rmse:3.09637
[2600]	validation_0-rmse:3.06670
[2700]	validation_0-rmse:3.04429
[2800]	validation_0-rmse:3.01905
[2900]	validation_0-rmse:3.00234
[3000]	validation_0-rmse:2.97569
[3100]	validation_0-rmse:2.95732
[3200]	validation_0-rmse:2.92841
[3300]	validation_0-rmse:2.90339
[3400]	validation_0-rmse:2.87968
[3500]	validation_0-rmse:2.86506
[3600]	validation_0-rmse:2.85040
[3700]	validation_0-rmse:2.83610
[3800]	validation_0-rmse:2.82018
[3900]	validation_0-rmse:2.80570
[4000]	validation_0-rmse:2.79272
[4100]	validation_0-rmse:2.77966
[4200]	validation_0-rmse:2.76664
[4300]	validation_0-rmse:2.75051
[4400]	validation_0-rmse:2.73061
[4500]	validation_0-rmse:2.71674
[4600]	validation_0-rmse:2.70519
[4700]	validation_0-rmse:2.69394
[4800]	validation_0-rmse:2.68045
[4900]	validation_0-rmse:2.66875
[4999]	validation_0-rmse:2.65820

In [107]:
pred = []
for app in app_cols:
    pred.append(regressor[app].predict(X_test))

In [112]:
def Precision_energy_based_fixed(y_predict, y_target, alpha = 1e-6):
    assert y_predict.shape[0] == y_target.shape[0], 'samples number not match'
    assert y_predict.shape[1] == y_target.shape[1], 'number of appliances not match'
    denominator = y_predict.sum(axis = 0) 
    numerator = np.minimum(y_predict, y_target).sum(axis = 0) 
    return (numerator + alpha) / (denominator + alpha)
def Recall_energy_based_fixed(y_predict, y_target, alpha = 1e-6):
    assert y_predict.shape[0] == y_target.shape[0], 'samples number not match'
    assert y_predict.shape[1] == y_target.shape[1], 'number of appliances not match'
    denominator = y_target.sum(axis = 0)
    numerator = np.minimum(y_predict, y_target).sum(axis = 0)
    return (numerator + alpha) / (denominator + alpha)
def F1_energy_based_fixed(y_predict, y_target, alpha = 1e-6):
    assert y_predict.shape[0] == y_target.shape[0], 'samples number not match'
    assert y_predict.shape[1] == y_target.shape[1], 'number of appliances not match'
    numerator = np.minimum(y_predict, y_target).sum(axis = 0)
    p_denominator = y_predict.sum(axis = 0)
    r_denominator = y_target.sum(axis = 0)
    precision = (numerator + alpha) / (p_denominator + alpha)
    recall = (numerator + alpha) / (r_denominator + alpha)
    return 2 * precision * recall / (precision + recall)
def NEP_fixed(y_predict, y_target, alpha = 1e-6):
    assert y_predict.shape[0] == y_target.shape[0], 'samples number not match'
    assert y_predict.shape[1] == y_target.shape[1], 'number of appliances not match'
    denominator = y_target.sum(axis = 0)
    numerator = np.abs(y_target - y_predict).sum(axis = 0)
    return (numerator + alpha) / (denominator + alpha)

In [116]:
overall_pred = pd.DataFrame(pred).transpose()
overall_pred

,0,1,2,3,4,5,6,7,8
0,20.973866,8.070931,8.358551,7.070478,0.026441,-0.649233,6.697180,0.243353,-1.959019
1,14.283939,1.218697,7.330341,6.438416,-17.489367,-0.045115,6.679277,-0.080858,-1.991928
2,9.927193,2.505585,6.157059,6.182587,-0.186359,0.912720,6.489318,0.681019,-1.980535
3,16.033241,12.257490,7.995152,8.645664,1.038141,1.382908,6.860340,0.268932,-2.348862
4,18.186836,6.091258,6.010300,10.150900,0.870025,0.770120,6.049146,0.293678,-2.128759
...,...,...,...,...,...,...,...,...,...
69995,53.749298,9.188641,3.144482,0.807602,-0.033690,-0.050292,-0.887254,-0.178946,-0.057002
69996,55.388710,8.439578,3.727341,1.220609,-0.033690,-0.031499,-0.408772,-0.194483,-0.038330
69997,27.625565,6.427782,3.156006,-0.606904,-0.033690,-0.023512,-0.458074,-0.201773,-0.037447
69998,11.904821,215.663467,1689.061401,-1.249819,14.911163,138.630234,3.005446,-132.509369,-1.970449
69999,0.746296,223.343948,1598.068481,-0.828449,-9.953123,260.482483,3.174419,-188.625137,-1.580068

In [117]:
overall_pred = overall_pred.clip(lower=0)

In [118]:
F1_energy_based_fixed(overall_pred.to_numpy(), y_test.reset_index(drop = True).drop(columns = ['remain']).to_numpy()).mean()

np.float64(0.4496528031596347)

In [119]:
Precision_energy_based_fixed(overall_pred.to_numpy(), y_test.reset_index(drop = True).drop(columns = ['remain']).to_numpy()).mean()

np.float64(0.4596769670990869)

In [120]:
Recall_energy_based_fixed(overall_pred.to_numpy(), y_test.reset_index(drop = True).drop(columns = ['remain']).to_numpy()).mean()

np.float64(0.466026959457465)

In [121]:
NEP_fixed(overall_pred.to_numpy(), y_test.reset_index(drop = True).drop(columns = ['remain']).to_numpy()).mean()

np.float64(1.440196969855692)